# Generated by Django 3.2.9 on 2022-01-20 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20220120_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('agent', models.CharField(max_length=255)),
                ('receptor_name', models.CharField(max_length=255)),
                ('receptor_charge', models.CharField(max_length=255)),
                ('beneficiaries', models.CharField(max_length=255)),
                ('partners', models.CharField(max_length=255)),
                ('tasks', models.CharField(max_length=255)),
                ('subsidies', models.CharField(max_length=2)),
                ('subsidies_what', models.CharField(max_length=2)),
                ('links', models.CharField(max_length=2)),
                ('claim', models.CharField(default='0', max_length=5000)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visits.visit')),
            ],
        ),
    ]
