# Generated by Django 3.2.9 on 2022-01-24 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_by'),
        ('visits', '0005_visit_act_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='claim',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='claims.claim'),
        ),
    ]
