# Generated by Django 3.2.9 on 2022-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_act_claim_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='allday',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
