# Generated by Django 3.2.9 on 2021-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
