# Generated by Django 3.2.9 on 2021-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finish',
            field=models.DateTimeField(null=True),
        ),
    ]
