# Generated by Django 3.2.9 on 2021-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hour',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
