# Generated by Django 3.2.9 on 2021-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20211216_1055'),
        ('events', '0008_alter_event_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='orgs',
            field=models.ManyToManyField(to='organizations.Org'),
        ),
    ]
