# Generated by Django 3.2.9 on 2021-11-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211112_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
