# Generated by Django 3.2.9 on 2021-11-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211114_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
