# Generated by Django 3.2.9 on 2022-02-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roac_num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
