# Generated by Django 3.2.9 on 2022-02-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_roac_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roac_num',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
    ]
