# Generated by Django 3.2.9 on 2022-02-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_roac_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roac_num',
        ),
    ]
