# Generated by Django 3.2.9 on 2021-12-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spot',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
