# Generated by Django 3.2.9 on 2021-12-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finish',
        ),
    ]
