# Generated by Django 3.2.9 on 2022-01-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_str',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
