# Generated by Django 3.2.9 on 2021-11-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.IntegerField(max_length=11, unique=True, verbose_name='Cuit')),
                ('email', models.EmailField(max_length=25, unique=True, verbose_name='Email')),
                ('contrasena', models.IntegerField(verbose_name='Contrasena')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre completo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Numero telefonico')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
