# Generated by Django 3.2.9 on 2021-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuit',
            field=models.IntegerField(unique=True, verbose_name='Cuit'),
        ),
    ]
