# Generated by Django 3.2.9 on 2021-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_rename_visit_name_activity_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created',
        ),
        migrations.AddField(
            model_name='activity',
            name='hour',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
