# Generated by Django 3.2.9 on 2021-12-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_activity_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_name',
            new_name='activity_type',
        ),
    ]
