# Generated by Django 3.2.9 on 2022-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_rename_activity_name_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allday',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
