# Generated by Django 3.2.9 on 2022-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_activity_allday'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='communes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
