# Generated by Django 3.2.9 on 2022-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='orgs_names',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
