# Generated by Django 3.2.9 on 2021-12-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hour',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
