# Generated by Django 3.2.9 on 2021-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20211216_1055'),
        ('visits', '0003_alter_visit_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_org',
        ),
        migrations.AddField(
            model_name='visit',
            name='observation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='orgs',
            field=models.ManyToManyField(to='organizations.Org'),
        ),
    ]
