# Generated by Django 3.2.9 on 2022-01-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20220124_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='act_id',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
