# Generated by Django 3.2.9 on 2021-12-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20211216_1055'),
        ('visits', '0004_auto_20211223_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='orgs',
        ),
        migrations.AddField(
            model_name='visit',
            name='org',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='organizations.org'),
            preserve_default=False,
        ),
    ]
