# Generated by Django 3.2.9 on 2021-12-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_auto_20211228_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='org',
            field=models.CharField(default='0', max_length=5000),
        ),
    ]
