# Generated by Django 3.2.9 on 2021-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_visit_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='org_name',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
