# Generated by Django 3.2.9 on 2022-01-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_act_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='claim_exist',
            field=models.CharField(default='Si', max_length=3),
            preserve_default=False,
        ),
    ]
