# Generated by Django 3.2.9 on 2022-01-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_rename_categoria_claim_category'),
        ('visits', '0008_visit_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='claim',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='claims.claim'),
        ),
    ]
