# Generated by Django 3.2.9 on 2021-12-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='enrolled',
            field=models.DateTimeField(null=True),
        ),
    ]
