# Generated by Django 3.2.9 on 2021-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20211216_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='igj',
            field=models.CharField(default='No', max_length=2),
        ),
        migrations.AlterField(
            model_name='org',
            name='roac',
            field=models.CharField(default='No', max_length=2),
        ),
    ]
