# Generated by Django 3.2.9 on 2022-02-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20211228_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='certificate',
            field=models.FileField(default='', upload_to='roac/certificate/'),
        ),
        migrations.AddField(
            model_name='org',
            name='expiration_mail',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='org',
            name='signed',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='org',
            name='igj',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='org',
            name='roac',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.CreateModel(
            name='Roac_orgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.org')),
            ],
        ),
    ]
