# Generated by Django 3.2.9 on 2022-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20220107_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='certificate',
            field=models.FileField(default='', upload_to='roac/certificate/'),
        ),
    ]
