# Generated by Django 3.2.9 on 2022-02-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_org_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roac_orgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.org')),
            ],
        ),
    ]
