# Generated by Django 3.2.9 on 2022-02-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_roac_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='expiration_mail',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
