# Generated by Django 3.2.9 on 2021-12-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_auto_20211216_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_name', models.CharField(max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('activity_org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.org')),
            ],
        ),
    ]
