# Generated by Django 3.2.9 on 2021-12-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='visit_name',
            new_name='activity_name',
        ),
    ]
