# Generated by Django 3.2.9 on 2021-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20211221_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hour',
            field=models.CharField(default='00:00:00', max_length=255, null=True),
        ),
    ]
