# Generated by Django 3.2.9 on 2022-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='by',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
