# Generated by Django 3.2.9 on 2022-01-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='Categoria',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
