# Generated by Django 3.2.9 on 2021-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('dpto', models.CharField(max_length=5)),
                ('nhood', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=3)),
                ('areas', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('igj', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('public', models.CharField(default='No especificado', max_length=255)),
                ('postal_code', models.CharField(default='No especificado', max_length=255)),
                ('domain', models.CharField(default='No especificado', max_length=255)),
                ('roac', models.BooleanField(default=False)),
                ('doc', models.FileField(default='', upload_to='roac/doc/')),
                ('state', models.CharField(default='No registrada', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('renoved', models.DateTimeField(null=True)),
                ('expiration', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
