# Generated by Django 3.2.9 on 2021-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('dpto', models.CharField(max_length=5)),
                ('nhood', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=3)),
                ('areas', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('igj', models.BooleanField(default=False)),
                ('public', models.CharField(default='No especificado', max_length=255)),
                ('postal_code', models.CharField(default='No especificado', max_length=10)),
                ('domain', models.CharField(default='No especificado', max_length=255)),
                ('roac', models.BooleanField(default=False)),
                ('nota_solicitud_inscripcion', models.FileField(upload_to='Org')),
                ('acta_libro_actas', models.FileField(upload_to='Org')),
                ('acta_asamblea', models.FileField(upload_to='Org')),
                ('estatuto_social', models.FileField(upload_to='Org')),
                ('nomina_comision', models.FileField(upload_to='Org')),
                ('dni_comision', models.FileField(upload_to='Org')),
                ('nomina_asociados', models.FileField(upload_to='Org')),
                ('sede_social', models.FileField(upload_to='Org')),
                ('abl', models.FileField(upload_to='Org')),
                ('extra', models.FileField(upload_to='Org')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
