# Generated by Django 3.2.9 on 2021-12-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.EmailField(default='jpkitro@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='org',
            name='mobile',
            field=models.CharField(default='jpkitro@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
