# Generated by Django 3.2.9 on 2022-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20211228_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='igj',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='org',
            name='roac',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
